import type { Metadata } from "next";
import "./globals.css";
import "./layout.css";
import Navbar from "@/components/layout/Navbar";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Stay Scape",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Providers>
          <Navbar />
          
          {children}
          <Toaster position="bottom-right" />
        </Providers>
      </body>
    </html>
  );
}
